USE [master]
GO

/****** Object:  Database [xiaohe]    Script Date: 2018/11/9 星期五 19:35:46 ******/
DROP DATABASE [xiaohe]
GO

/****** Object:  Database [xiaohe]    Script Date: 2018/11/9 星期五 19:35:46 ******/
CREATE DATABASE [xiaohe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'xiaohe', FILENAME = N'F:\sqlserver2017\MSSQL14.MSSQLSERVER\MSSQL\DATA\xiaohe.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'xiaohe_log', FILENAME = N'F:\sqlserver2017\MSSQL14.MSSQLSERVER\MSSQL\DATA\xiaohe_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [xiaohe] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [xiaohe].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [xiaohe] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [xiaohe] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [xiaohe] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [xiaohe] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [xiaohe] SET ARITHABORT OFF 
GO

ALTER DATABASE [xiaohe] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [xiaohe] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [xiaohe] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [xiaohe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [xiaohe] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [xiaohe] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [xiaohe] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [xiaohe] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [xiaohe] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [xiaohe] SET  DISABLE_BROKER 
GO

ALTER DATABASE [xiaohe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [xiaohe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [xiaohe] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [xiaohe] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [xiaohe] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [xiaohe] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [xiaohe] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [xiaohe] SET RECOVERY FULL 
GO

ALTER DATABASE [xiaohe] SET  MULTI_USER 
GO

ALTER DATABASE [xiaohe] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [xiaohe] SET DB_CHAINING OFF 
GO

ALTER DATABASE [xiaohe] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [xiaohe] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [xiaohe] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [xiaohe] SET QUERY_STORE = OFF
GO

ALTER DATABASE [xiaohe] SET  READ_WRITE 
GO

